### ISSUE TITLE
Performance bump on fizzbuzz

### ISSUE THREAD

**Issue by lucasdavid** [debugmaster/kattis#1]
You don't have to iterate over all N integers in [fizzbuzz](https://github.com/debugmaster/kattis/blob/master/nodejs/src/fizzbuzz.ts). Just increment the smallest by its own factor `x` or `y`:
```py
from sacred import Experiment

ex = Experiment('fizzbuzz')

@ex.config
def my_config():
    x = 10
    y = 15
    n = 100

@ex.automain
def main(x, y, n):
    i, j = x, y
    window = 1

    while i <= n or j <= n:
        # _min = min(i, j)
        # if window < m:
        #     print(*range(window, _min), end=' ')
        # window = _min + 1

        if i == j:
            print('FizzBuzz', end=' ')
            i += x
            j += y
        elif i < j:
            print('Fizz', end=' ')
            i += x
        else:
            print('Buzz', end=' ')
            j += y

    print()
```

> Note: I commented `print(*range(window, _min), end=' ')` because this will print all integers (which is linear), hiding the performance improvement.

Anyways, executing your code with the following parameters takes 33 seconds:
```shell
python fizzbuzz.py with x=13 y=7 n=10000000 -F ./logs/fizzbuzz/
"start_time": "2018-08-28T02:19:37.457346",
"stop_time": "2018-08-28T02:20:10.759150"
```

While the code above takes only 22 seconds:
```shell
python fizzbuzz.py with x=13 y=7 n=10000000 -F ./logs/fizzbuzz/
"start_time": "2018-08-28T02:20:24.905657",
"stop_time": "2018-08-28T02:20:47.376358"
```

**Comment by debugmaster** [comment]
I created #2 based on this solution @lucasdavid 

I was able to achieve 15 to 20% performance improvement. The new solution still iterates over all integers because `range()` is specific to Python.

Please feel free to have a look.

**Comment by debugmaster** [comment]
Nonetheless, the problem was not very worried about very big `N`'s because `1 ≤ X < Y ≤ N ≤ 100` .

**Comment by lucasdavid** [comment]
I think underscore has a range method too, but you probably doesn't have it as dependency. Y'all got any more of them challenges?
!["Y'all got any more of them?" meme](https://user-images.githubusercontent.com/1595030/44787572-e82f5080-ab6d-11e8-86b8-a83616c9ce77.png)

**Comment by debugmaster** [comment]
I was looking for native/built-in implementation because Kattis doesn't allow to specify project's dependencies.
